INSERT INTO tipos_producto (nombre_tipo) VALUES ('Frutas');
INSERT INTO tipos_producto (nombre_tipo) VALUES ('Verduras');
INSERT INTO tipos_producto (nombre_tipo) VALUES ('Mermeladas');
INSERT INTO tipos_producto (nombre_tipo) VALUES ('Conservas');
INSERT INTO tipos_producto (nombre_tipo) VALUES ('Otros');

INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 123','fel4ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1823','ang5elica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 1243','felipe.cast5illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1923','angel6ica.v5enegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fal4sa 123','felipe.cast3illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle F3alsa 123','ange1lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fa2lsa 123','fel9ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Fa7lsa 123','ange9lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Cal8le Falsa 123','felipe.casti8llo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Ca3lle Falsa 123','angel1ica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 123','fel4ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1823','ang5elica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 1243','felipe.cast5illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1923','angel6ica.v5enegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fal4sa 123','felipe.cast3illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle F3alsa 123','ange1lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fa2lsa 123','fel9ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Fa7lsa 123','ange9lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Cal8le Falsa 123','felipe.casti8llo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Ca3lle Falsa 123','angel1ica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 123','fel4ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1823','ang5elica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 1243','felipe.cast5illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1923','angel6ica.v5enegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fal4sa 123','felipe.cast3illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle F3alsa 123','ange1lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fa2lsa 123','fel9ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Fa7lsa 123','ange9lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Cal8le Falsa 123','felipe.casti8llo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Ca3lle Falsa 123','angel1ica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 123','fel4ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1823','ang5elica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 1243','felipe.cast5illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1923','angel6ica.v5enegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fal4sa 123','felipe.cast3illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle F3alsa 123','ange1lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fa2lsa 123','fel9ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Fa7lsa 123','ange9lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Cal8le Falsa 123','felipe.casti8llo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Ca3lle Falsa 123','angel1ica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 123','fel4ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1823','ang5elica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 1243','felipe.cast5illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1923','angel6ica.v5enegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fal4sa 123','felipe.cast3illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle F3alsa 123','ange1lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fa2lsa 123','fel9ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Fa7lsa 123','ange9lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Cal8le Falsa 123','felipe.casti8llo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Ca3lle Falsa 123','angel1ica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 123','fel4ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1823','ang5elica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Falsa 1243','felipe.cast5illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Falsa 1923','angel6ica.v5enegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fal4sa 123','felipe.cast3illo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle F3alsa 123','ange1lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Calle Fa2lsa 123','fel9ipe.castillo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Calle Fa7lsa 123','ange9lica.venegas@gmail.com','We Love Pizza','+56987535685');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Felipe','Castillo','Cal8le Falsa 123','felipe.casti8llo@gmail.com',null,'+56999599344');
INSERT INTO cliente(nombre, apellido,direccion,email,nombre_empresa,telefono) VALUES('Angelica','Venegas','Ca3lle Falsa 123','angel1ica.venegas@gmail.com','We Love Pizza','+56987535685');


INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Manzana Verde',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Manzana Roja',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Lechuga Escarola',100, 1000,1500,'KG',false);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Champiniones',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Mermelada de Mora',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Oregano',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Conserva',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Manzana Verde',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Manzana Roja',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Lechuga Escarola',100, 1000,1500,'KG',false);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Champiniones',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Mermelada de Mora',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Oregano',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Conserva',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Manzana Verde',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Manzana Roja',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Lechuga Escarola',100, 1000,1500,'KG',false);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Champiniones',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Mermelada de Mora',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Oregano',100, 1000,1500,'KG',true);
INSERT INTO producto(imagen, nombre_producto, stock, ultimo_precio_compra, ultimo_precio_venta, unidad_medida, visibilidad) VALUES('imagen','Conserva',100, 1000,1500,'KG',true);


INSERT INTO usuario(nombre,nombre_usuario,email,password) VALUES('admin','admin','admin@admin.com','$2a$10$/RgW9V3nbAemUKs6apisnuKWjVrLbGaKvDIK2XI0SrtKvDZwjCH.W');
INSERT INTO usuario(nombre,nombre_usuario,email,password) VALUES('trabajador','trabajador','trabajador@admin.com','$2a$10$/RgW9V3nbAemUKs6apisnuKWjVrLbGaKvDIK2XI0SrtKvDZwjCH.W');
INSERT INTO usuario(nombre,nombre_usuario,email,password) VALUES('cliente','cliente','cliente@admin.com','$2a$10$/RgW9V3nbAemUKs6apisnuKWjVrLbGaKvDIK2XI0SrtKvDZwjCH.W');

INSERT INTO rol(rol_nombre) VALUES('ROLE_ADMIN');
INSERT INTO rol(rol_nombre) VALUES('ROLE_TRABAJADOR');
INSERT INTO rol(rol_nombre) VALUES('ROLE_CLIENTE');

INSERT INTO usuario_rol(usuario_id, rol_id) VALUES(1,1);
INSERT INTO usuario_rol(usuario_id, rol_id) VALUES(1,2);
INSERT INTO usuario_rol(usuario_id, rol_id) VALUES(2,2);
INSERT INTO usuario_rol(usuario_id, rol_id) VALUES(3,3);
